### REGISTER ADMIN
POST http://localhost:5005/auth-api/users
Content-Type: application/json

{
  "name": "admin1",
  "email": "admin1@gmail.com",
  "password": "ADMIN1",
  "role": "ADMIN"
}


### LOGIN ADMIN
POST http://localhost:5005/auth-api/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "12345"
}


### LOGOUT
GET http://localhost:5005/auth-api/logout


### GET PENDING CAMPAIGNS
GET http://localhost:5005/admin-api/campaigns/pending

### APPROVE CAMPAIGN
PUT http://localhost:5005/admin-api/campaigns/approve/69f9a1eb8f0093712941454a

### REJECT CAMPAIGN
PUT http://localhost:5005/admin-api/campaigns/reject/69facc7d17f9ea50c0313c86

### CHECK AUTH
GET http://localhost:5005/auth-api/check-auth