### REGISTER USER
POST http://localhost:5005/auth-api/users
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@gmail.com",
  "password": "user1",
  "role": "USER"
}



### LOGIN USER
POST http://localhost:5005/auth-api/login
Content-Type: application/json

{
  "email": "kaustubh@gmail.com",
  "password": "12345"
}


### LOGOUT
GET http://localhost:5005/auth-api/logout

### GET USER DETAILS
GET http://localhost:5005/user-api/users

### UPDATE USER PROFILE
PUT http://localhost:5005/user-api/users
Content-Type: application/json

{
  "name": "user2",
  "profileImageURL": "https://dummyimage.com/profile.png"
}

### CHANGE PASSWORD
PUT http://localhost:5005/auth-api/password
Content-Type: application/json

{
  "currentPassword": "user1",
  "newPassword": "user2"
}

### DELETE USER
DELETE http://localhost:5005/user-api/users